from pathlib import Path
from html import escape
root=Path(__file__).parent/'dist'
nav=[('index','任務首頁'),('checkin','啟航暖身'),('guide','指引航海圖'),('literacy','AI 素養補給站'),('lesson','教案設計工坊'),('checkout','回校行動港'),('dashboard','航行儀表板'),('resources','教材補給箱'),('admin','管理模式')]
def finish(n):return f'<div class="task-footer"><p>完成練習後，為自己的航程留下一個記號。</p><button class="button" data-task="{n}" aria-pressed="false">完成這張任務卡</button></div>'
def task(n,title,sub,body):return f'<section class="card"><div class="task-header"><span class="task-no">{n:02}</span><div><h2>{title}</h2><p>{sub}</p></div></div>{body}{finish(n)}</section>'
def steps(items):return '<div class="steps">'+''.join(f'<div class="step"><strong>{a}</strong>{b}</div>' for a,b in items)+'</div>'
def field(name,label,value='',area=False):return f'<div class="field"><label for="{name}">{label}</label>'+ (f'<textarea id="{name}" name="{name}">{value}</textarea>' if area else f'<input id="{name}" name="{name}" value="{escape(value)}">')+'</div>'
def noteform(body):
 mappings=[('expectation','submitLearningGoal',{'expectation':'goal'}),('dimension','submitSelfCheck',{'goal':'nextStep'}),('risk-scene','submitRiskLessonTask',{'risk-scene':'scenario','risk-action':'studentTask'}),('lesson-choice','submitPromptRevision',{'lesson-choice':'lessonTitle','phase':'aiTiming','prompt':'revisedPrompt'}),('feedback','submitFeedback',{'feedback':'borrowIdea'}),('highlight','submitExitTicket',{'action':'firstStep'})]
 for marker,action,mapping in mappings:
  if 'name="'+marker+'"' not in body: continue
  for old,new in mapping.items(): body=body.replace('name="'+old+'"','name="'+new+'"')
  if action=='submitRiskLessonTask': body+=field('riskType','風險類型','AI 幻覺')+field('learningEvidence','學生要交的學習證據','',True)
  if action=='submitPromptRevision': body+=field('originalPrompt','修改前的 Prompt','',True)
  if action=='submitFeedback': body+=field('targetRecordId','回饋對象的組別','')+field('suggestion','建議夥伴再試什麼？','',True)
  return '<form data-api-action="'+action+'">'+body+'<button type="submit" class="button secondary" data-save>送出紀錄</button><p class="result" data-submit-status role="status" aria-live="polite"></p></form>'
 raise ValueError('Unmapped form')
stations=[('checkin','☀','01','啟航暖身','遇見身旁的夥伴，帶著一個好奇的問題出發。','10 分鐘','1,2'),('guide','⌖','02','指引航海圖','看懂指引骨架，找到自己的 AI 教學位置。','20 分鐘','3,4'),('literacy','◈','03','AI 素養補給站','辨識風險，把安全提醒變成學生會做的動作。','60 分鐘','5,6,9'),('lesson','✎','04','教案設計工坊','試一段 Prompt，讓 AI 幫學生把想法說清楚。','80 分鐘','7,8'),('checkout','⚑','05','回校行動港','回看今天的收穫，帶走一個做得到的第一步。','10 分鐘','10')]
home='<div class="section-head"><h2>今天的任務航線</h2><p>5 個停靠站 · 10 張任務卡 · 180 分鐘</p></div><div class="station-grid">'
for route,icon,num,title,desc,time,ids in stations:
 home+=f'<article class="station"><div class="station-top"><span class="station-icon" aria-hidden="true">{icon}</span><span class="pill">{time}</span></div><h3>{num}　{title}</h3><p>{desc}</p><div class="station-foot"><span data-station-tasks="{ids}"></span><a class="text-link" href="{route}.html">進入任務 →</a></div></article>'
home+='<article class="station"><div class="station-top"><span class="station-icon" aria-hidden="true">▤</span><span class="pill">隨時取用</span></div><h3>教材補給箱</h3><p>指引摘要、教案示例與口訣卡，在需要的時候給你一點支持。</p><div class="station-foot"><span>4 份示範資源</span><a class="text-link" href="resources.html">打開補給箱 →</a></div></article></div><div class="route-banner"><div><strong>準備好了，就從下一個停靠站開始。</strong><p>先完成報到，再從啟航暖身開始。</p></div><a class="button" href="guide.html">繼續航程 →</a></div>'
checkin=task(1,'先停一下，遇見夥伴','兩兩分享 · 6 分鐘',steps([('01 深呼吸','三次深呼吸，微笑和夥伴打招呼。'),('02 各說兩分鐘','分享一次使用 AI 的驚艷，或一個還在擔心的問題。'),('03 聽見彼此','回應夥伴：「我聽見你在意的是……」')])+'<div class="button-row"><output class="timer" id="timer" aria-label="剩餘時間">06:00</output><button class="button secondary" id="start-timer">開始 6 分鐘</button><button class="button secondary" id="reset-timer">重設</button></div>')
checkin+=task(2,'打開地圖，看懂今天要去哪裡','看懂三小時航程 · 2 分鐘','<div class="note">看懂指引 20 分 → 看見風險 60 分 → 設計教案 80 分 → 回校行動 10 分。加上開場暖身 10 分，共 180 分鐘。</div>'+noteform(field('expectation','今天最想帶走什麼？','一個讓學生保留思考的 AI 提問方式。')))
guide=task(3,'快速翻書，找到指引骨架','指引速查 · 6 分鐘',steps([('風帆：趨勢與願景','指引第一章，幫我們看見航行方向。'),('船身：策略與案例','指引第二至第七章，承載課堂的實際做法。'),('龍骨：以人為中心','教學決定由人掌握，守住學生的學習。')])+'<fieldset class="choices"><legend>這次翻書，我找到了……</legend>'+''.join(f'<label class="choice"><input type="checkbox">{s}</label>' for s in ['一個與趨勢願景有關的重點','一個想帶回課堂的策略','一個還想繼續追問的問題'])+'</fieldset>')
guide+=task(4,'照一照自己的 AI 教學位置','自我定位 · 5 分鐘',noteform('<div class="two-col"><div class="field"><label for="dimension">我想補強的面向</label><select id="dimension" name="dimension"><option>AI 倫理</option><option>AI 基礎與技術</option><option selected>AI 賦能教學</option><option>AI 促進專業發展</option></select></div><div class="field"><label for="level">我目前的位置</label><select id="level" name="level"><option>取得理解</option><option selected>深化應用</option><option>創造轉型</option></select></div></div>'+field('goal','我的下一步','試著把直接給答案的提問，改成分步提示。')))
literacy=task(5,'練一組學生聽得懂的防護口訣','STEP 情境演練 · 4 分鐘','<p class="muted">群組傳來一張「明天停課」截圖，你會先怎麼做？（虛構情境）</p><fieldset class="choices"><legend>選一個做法</legend><label class="choice"><input type="radio" name="risk-answer" value="share">很多人都轉傳了，應該可以相信。</label><label class="choice"><input type="radio" name="risk-answer" value="source">找到原始公告，核對發布單位與日期。</label><label class="choice"><input type="radio" name="risk-answer" value="ai">問 AI 是不是真的，直接採用它的答案。</label></fieldset><button class="button secondary" id="check-risk">看看判斷線索</button><div id="risk-result" class="result" role="status"></div>')
literacy+=task(6,'把一個 AI 風險變成課堂小任務','小組研討 · 15 分鐘',noteform(field('risk-scene','風險情境','AI 回答了錯誤的課文資訊，學生直接抄進作業。',True)+field('risk-action','學生要做什麼？','圈出可疑主張，找原文比對，交出修正句與來源。',True)))
literacy+=task(9,'用紅黃綠燈劃出 AI 使用界線','小組討論 · 10 分鐘',steps([('綠燈：可以用','練習時請 AI 提示，學生自己說出推理。'),('黃燈：需說清楚','用 AI 潤飾初稿，附上使用方式與修改前後。'),('紅燈：不能用','獨立評量交 AI 代答，或輸入可識別個資。')])+'<p class="muted">以上為示範規範，實際界線請配合學習目標與學校規定。</p>')
lesson=task(7,'讓 AI 幫學生想清楚','選教案、找時機、測試 Prompt · 25 分鐘',noteform('<div class="two-col"><div class="field"><label for="lesson-choice">示範教案</label><select id="lesson-choice" name="lesson-choice"><option>國語《建築界的長頸鹿》</option><option>數學《三角形三心》</option></select></div>'+field('phase','AI 介入時機','組內共學：拆解說明文的結構')+'</div>'+field('prompt','試著把這段 Prompt 改成你的版本','你是四年級的閱讀學習夥伴。請協助我理解說明文的總說、分說與總結。一次只問一個問題，等我回答再給提示。先不要給完整答案，最後請我用自己的話說明。',True))+'<div class="button-row" style="margin-top:14px"><button class="button secondary" id="copy-prompt">複製 Prompt</button></div><div class="note">檢查：AI 有沒有直接代答？學生最後留下什麼學習證據？</div>')
lesson+=task(8,'把作品貼上牆，互相借一個好點子','上傳與互評 · 25 分鐘',steps([('2 分鐘：說設計','我們想解決哪個學習難點？'),('2 分鐘：說 Prompt','我們怎麼測試，又改了什麼？'),('1 分鐘：聽回饋','我想借用……我建議再試……')])+'<div class="note"><strong>海星組的示範作品</strong><br>先請學生指出課文中的分說段，再讓 AI 追問理由。學生交出原文標記與自己的說明。</div>'+noteform(field('feedback','給夥伴一句回饋','我想借用「先指出原文」這個動作，讓對話更有依據。',True)))
checkout=task(10,'帶走一個回校後做得到的第一步','Check out · 8 分鐘',noteform(field('highlight','今天最亮的一張卡','任務卡 7：把 Prompt 改成一次只問一題。')+field('blocker','目前還卡在哪裡？','如何從學生的回答判斷他真的理解？')+field('action','我的回校第一步','下週的四年級國語課，試一次分步提示，觀察學生能否用自己的話說明。',True)))+'<div class="route-banner"><div><strong>真正掌舵的，始終是看見學生的你。</strong><p>從一堂課、一個問題開始，就很好。</p></div><a class="button" href="dashboard.html">回看航程 →</a></div>'
dashboard='<section class="card"><h2>講師投影控制台</h2><p>公開投影以組別呈現；未報到的成果顯示「未分組」。</p><button id="dashboard-refresh" class="button">重新整理全部資料</button><p id="dashboard-status" role="status" aria-live="polite"></p><p class="muted">投影前請先閱讀成果內容；可隱藏不適合公開的卡片。自由文字仍需由講師確認。</p></section><div id="dashboard-panels"></div><dialog id="projection-dialog" aria-labelledby="projection-title"><header><h2 id="projection-title"></h2><button id="projection-close" class="button">結束投影（Esc）</button></header><div id="projection-content"></div></dialog>'
resources='<section class="card"><h2>這趟航程的隨身補給</h2><p class="muted">先用摘要認識資源。本版為示範內容，尚未接上正式教材下載。</p>'
for title,desc,body in [('115 年數位與 AI 教學指引','指引摘要 · 對應任務卡 3、4','以風帆看趨勢與願景，以船身看策略與案例，以龍骨守住以人為中心的核心價值。'),('AI 防護口訣卡','口訣摘要 · 對應任務卡 5、6','STEP：看來源、看時間、看證據、看觀點。THINK：先試試、提示我、自己詮釋、換題再做、確認懂。FACT：找出可疑、追問依據、查證比對、修正轉化。'),('AIPACK 教案示例','國語與數學 · 對應任務卡 7、8','國語《建築界的長頸鹿》聚焦說明文結構；數學《三角形三心》聚焦定義辨識與性質驗證。從學科難點決定 AI 的介入時機。'),('回校行動紀錄','行動句型 · 對應任務卡 10','我會在＿＿時間，和＿＿班級嘗試＿＿做法，透過＿＿證據觀察學生的學習。')]:resources+=f'<details><summary>{title}<br><span class="muted" style="font-size:14px;font-weight:400">{desc}</span></summary><p>{body}</p></details>'
resources+='</section><div class="note">口訣與教案名稱依本次 B3 教材整理；表單內容、小組與統計數據均為示範。</div>'
pages={'index':('B3 AI 教學導航任務站','一起完成 10 張任務卡，把一個好點子帶回課堂。',home),'checkin':('啟航暖身','先與人連結，再帶著好奇心迎向 AI 教學。',checkin),'guide':('指引航海圖','翻一翻、找一找，找到最靠近自己課堂需求的那一頁。',guide),'literacy':('AI 素養補給站','看見風險，也練習把判斷權留在人手中。',literacy),'lesson':('教案設計工坊','從一個學習難點開始，讓 AI 成為學生思考的夥伴。',lesson),'checkout':('回校行動港','收好今天的亮點，選一個下週就能嘗試的小行動。',checkout),'dashboard':('航行儀表板','看見全班的想法，讓每一份成果成為共學的起點。',dashboard),'resources':('教材補給箱','需要方向的時候，回來翻一翻。',resources)}
pages['admin']=('管理模式','連接 Google 表單，或設定網站的試算表 API。','<section class="card" id="admin-settings"></section>')
for key,(title,sub,body) in pages.items():
 links=''.join(f'<a href="{route}.html"'+(' aria-current="page"' if route==key else '')+f'><span class="nav-num">{i+1:02}</span>{label}</a>' for i,(route,label) in enumerate(nav))
 html=f'''<!doctype html><html lang="zh-Hant"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="B3 三小時 AI 教學工作坊，十張任務卡的靜態示範導航站。"><title>{title}｜B3 教學導航</title><link rel="icon" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 40 40'%3E%3Crect width='40' height='40' rx='12' fill='%23163e50'/%3E%3Cpath d='M20 5 29 29 20 25 11 29Z' fill='%23fff0b9'/%3E%3C/svg%3E"><link rel="stylesheet" href="styles.css"><script src="assets/js/config.js" defer></script><script src="assets/js/api-schema.js" defer></script><script src="assets/js/aggregates.js" defer></script><script src="assets/js/dashboard-data.js" defer></script><script src="assets/js/sheet-contract.js" defer></script><script src="assets/js/sheet-adapter.js" defer></script><script src="assets/js/privacy-validation.js" defer></script><script src="assets/js/api.js" defer></script><script src="assets/js/interactions.js" defer></script><script src="assets/js/dashboard.js" defer></script><script src="assets/js/workshop.js" defer></script><script src="assets/js/admin.js" defer></script><script src="app.js" defer></script></head><body><a class="skip" href="#main">跳至主要內容</a><aside class="sidebar"><a class="brand" href="index.html"><span class="brand-mark" aria-hidden="true">⌖</span><span>B3 教學導航<small>AI LEARNING VOYAGE</small></span></a><button class="menu-toggle" aria-controls="navigation" aria-expanded="false">選單 ☰</button><p class="nav-label">我的學習航程</p><nav class="nav" id="navigation" aria-label="主要導覽">{links}</nav><div class="sidebar-bottom"><div class="crew"><span class="avatar">林</span><strong>我的學習航程</strong>以報到組別參與</div></div></aside><div class="workspace"><header class="topbar"><span>B3 工作坊 / {dict(nav)[key]}</span><div class="top-actions"><span class="demo-badge">示範模式</span><a class="home-link" href="index.html">⌂ 返回首頁</a></div></header><main id="main"><section class="hero"><div class="eyebrow">B3 WORKSHOP · 教育部數位教學指引培力</div><h1>{title}</h1><p>{sub}</p></section><section class="progress-panel" aria-label="任務進度"><div class="progress-title">我的航程<strong><span data-count>2</span> / 10</strong></div><div class="progress-track" role="progressbar" aria-label="完成任務卡數" aria-valuemin="0" aria-valuemax="10" aria-valuenow="2"><div class="progress-fill" data-progress></div></div><span class="progress-caption">每完成一張卡，就向前一步</span></section>{body}</main><footer class="footer"><span>B3 AI 教學導航任務站 · 三小時共學航程</span><span>示範教材 · 請勿填寫身分證號、電話或住址；公開投影以組別呈現</span></footer></div><div id="toast" class="toast" role="status" aria-live="polite"></div><noscript>請啟用 JavaScript 以體驗任務進度與示範互動。導覽和教材摘要仍可直接閱讀。</noscript></body></html>'''
 (root/f'{key}.html').write_text(html,encoding='utf8')
import shutil
for asset in (Path(__file__).parent.parent/'public/assets/js').glob('*.js'):
 (root/'assets/js').mkdir(parents=True,exist_ok=True)
 shutil.copy2(asset,root/'assets/js'/asset.name)
print('Created 8 static pages and synchronized API assets.')
