function b3Book_(){const id=PropertiesService.getScriptProperties().getProperty('SPREADSHEET_ID');if(!id)b3Fail_('NOT_CONFIGURED','請在 Script Properties 設定 SPREADSHEET_ID。');return SpreadsheetApp.openById(id);}
function b3Workshop_(id){const configured=PropertiesService.getScriptProperties().getProperty('WORKSHOP_ID')||'b3-demo';if(id!==undefined&&id!==configured)b3Fail_('WRONG_WORKSHOP','場次與這份試算表設定不符。');return configured;}
function b3Sheet_(book,spec,create){let sheet=book.getSheetByName(spec.sheet);if(!sheet&&create)sheet=book.insertSheet(spec.sheet);if(!sheet)return null;if(!sheet.getLastRow()){if(create){sheet.getRange(1,1,1,spec.fields.length).setValues([spec.fields]);sheet.setFrozenRows(1);}return sheet;}const headers=sheet.getRange(1,1,1,spec.fields.length).getValues()[0];if(headers.some((v,i)=>v!==spec.fields[i])||(sheet.getLastColumn&&sheet.getLastColumn()!==spec.fields.length))b3Fail_('SCHEMA_MISMATCH',spec.sheet+' 欄位不符，請先備份並依 schema 遷移。');return sheet;}
function setupSheets(){const lock=LockService.getScriptLock();if(!lock.tryLock(10000))b3Fail_('BUSY','請稍後再試。');try{const book=b3Book_();Object.values(B3_SHEET_CONTRACT).concat([{sheet:'settings',fields:['key','value','note']}]).forEach(s=>b3Sheet_(book,s,true));SpreadsheetApp.flush();}finally{lock.releaseLock();}}
function doGet(e){return b3Respond_(()=>{const p=e&&e.parameter||{};if(p.action==='getReceipt'){const id=b3Id_(p.requestId,'requestId');const saved=CacheService.getScriptCache().get('receipt:'+id);if(!saved)b3Fail_('RECEIPT_PENDING','尚未取得提交確認，請稍後核對資料。');return JSON.parse(saved);}if(p.action!=='getDashboardData')b3Fail_('METHOD_NOT_ALLOWED','GET 僅支援 getDashboardData。');return b3Dashboard_(p.workshopId);});}
function doPost(e){return b3Respond_(()=>{const raw=e&&e.postData&&e.postData.contents;if(typeof raw!=='string'||raw.length>60000)b3Fail_('INVALID_JSON','請提供有效 JSON，長度不超過 60000。');let body;try{body=JSON.parse(raw);}catch(_){b3Fail_('INVALID_JSON','JSON 格式錯誤。');}if(!b3Object_(body))b3Fail_('INVALID_REQUEST','本文必須是物件。');if(!b3Object_(body.payload))b3Fail_('INVALID_REQUEST','payload 必須是物件。');if(body.action==='getDashboardData')return b3Dashboard_(body.workshopId);if(!b3Own_(B3_SHEET_CONTRACT,body.action))b3Fail_('UNKNOWN_ACTION','不支援的 action。');const requestId=body.requestId?b3Id_(body.requestId,'requestId'):null;const data=b3Submit_(body);if(requestId)CacheService.getScriptCache().put('receipt:'+requestId,JSON.stringify(data),600);return data;});}
function b3Submit_(body){b3Workshop_(body.workshopId);const spec=B3_SHEET_CONTRACT[body.action];if(!b3Object_(body.payload))b3Fail_('INVALID_REQUEST','payload 必須是物件。');Object.keys(body.payload).forEach(k=>{if(!spec.fields.includes(k)||k==='timestamp')b3Fail_('UNKNOWN_FIELD','未定義或伺服器專用欄位：'+k);});const data={};spec.fields.filter(k=>k!=='timestamp').forEach(k=>{const v=body.payload[k];if(v!==undefined&&typeof v!=='string'&&typeof v!=='boolean'&&typeof v!=='number')b3Fail_('INVALID_FIELD','欄位必須是文字或單一數值。');data[k]=v===undefined?'':String(v).trim();if(data[k].length>(k==='keyword'?40:5000))b3Fail_('INVALID_FIELD','欄位過長：'+k);if(k.endsWith('_score')&&!/^[1-5]$/.test(data[k]))b3Fail_('INVALID_FIELD','四面向分數須為 1–5。');if(['gives_direct_answer','requires_reasoning','requires_comparison','requires_own_words'].includes(k)&&data[k]&&!['true','false'].includes(data[k]))b3Fail_('INVALID_FIELD','檢查欄位須為 true 或 false。');});if(spec.fields.includes('participant_id'))data.participant_id=b3Id_(data.participant_id||body.participantId,'participant_id');
try{b3PrivacyCheck(data);}catch(_){b3Fail_('SENSITIVE_DATA','請移除身分證號、電話或住址後再送出。');}b3RequiredFields(body.action).forEach(k=>{if(!data[k])b3Fail_('REQUIRED_FIELD','請填寫：'+k);});
const lock=LockService.getScriptLock();if(!lock.tryLock(10000))b3Fail_('BUSY','請稍後再試。');try{const book=b3Book_();if(spec.fields.includes('group_id')&&(!data.group_id||!data.name)&&data.participant_id){const people=b3Rows_(book,'submitParticipant');const p=people.filter(r=>r.participant_id===data.participant_id).pop();if(p){data.group_id=data.group_id||p.group_id;if(spec.fields.includes('name'))data.name=data.name||p.name;}}
const sheet=b3Sheet_(book,spec,true),timestamp=new Date().toISOString();data.timestamp=timestamp;sheet.getRange(sheet.getLastRow()+1,1,1,spec.fields.length).setValues([spec.fields.map(k=>b3Cell_(data[k]||''))]);SpreadsheetApp.flush();return{action:body.action,sheet:spec.sheet,timestamp,recordId:Utilities.getUuid()};}finally{lock.releaseLock();}}
function b3Rows_(book,action){const spec=B3_SHEET_CONTRACT[action],sheet=b3Sheet_(book,spec,false);if(!sheet||sheet.getLastRow()<2)return[];return sheet.getRange(2,1,sheet.getLastRow()-1,spec.fields.length).getValues().map(row=>Object.fromEntries(spec.fields.map((k,i)=>[k,row[i] instanceof Date?row[i].toISOString():b3ReadCell_(row[i])])));}
function b3Dashboard_(id){id=b3Workshop_(id);const book=b3Book_(),rows=[],counts={};Object.keys(B3_SHEET_CONTRACT).forEach(action=>{const entries=b3Rows_(book,action);counts[action]=entries.length;entries.forEach(d=>rows.push({action,participantId:d.participant_id||'group-'+d.group_id,timestamp:d.timestamp,data:b3FromSheet(action,d)}));});const projection=b3ProjectionData(rows);return{...b3InteractiveAggregate(rows),...projection,submissionCounts:counts,generatedAt:new Date().toISOString(),workshopId:id};}
