from pathlib import Path
import json
names=['participants','word_cloud','learning_goals','guide_treasure','ai_literacy_selfcheck','risk_case_cards','risk_lesson_tasks','prompt_revision','lesson_market','feedback','ai_rules_traffic_light','exit_ticket','settings']
cols=['participant_id,timestamp,name,school,group_id,role','timestamp,participant_id,name,group_id,mood,keyword,note','timestamp,participant_id,name,group_id,goal,reason','timestamp,group_id,sail_chapter,sail_quote,keel_quote,hull_chapter,hull_reason','timestamp,participant_id,name,group_id,ethics_score,tech_score,teaching_score,professional_score,strength,growth_need','timestamp,group_id,case_id,risk_type,strategy,student_reminder,practice_activity','timestamp,group_id,grade_level,risk_topic,student_scenario,student_task,teacher_reminder,learning_evidence','timestamp,group_id,lesson_title,ai_entry_point,original_prompt,gives_direct_answer,requires_reasoning,requires_comparison,requires_own_words,revised_prompt,revision_reason','timestamp,group_id,lesson_title,ai_entry_point,original_prompt,revised_prompt,avoid_thinking_replacement','timestamp,from_group_id,to_group_id,feedback_type,feedback_text','timestamp,group_id,green_items,yellow_items,red_items,class_rule','timestamp,participant_id,name,group_id,takeaway,stuck_point,first_action,support_needed','key,value,note']
old=json.loads(Path('public/assets/js/api-schema.js').read_text(encoding='utf8').split(' = ',1)[1].strip().rstrip(';'))
maps=[{'displayName':'name','groupName':'group_id'}, {'word':'keyword'}, {}, {'chapter':'sail_chapter','finding':'sail_quote','classroomQuestion':'hull_reason'}, {'ethicsScore':'ethics_score','basicsScore':'tech_score','teachingScore':'teaching_score','developmentScore':'professional_score','evidence':'strength','nextStep':'growth_need'}, {'riskType':'risk_type','scenario':'case_id','judgment':'strategy','strategy':'student_reminder'}, {'grade':'grade_level','riskType':'risk_topic','scenario':'student_scenario','studentTask':'student_task','reminder':'teacher_reminder','learningEvidence':'learning_evidence'}, {'lessonTitle':'lesson_title','aiTiming':'ai_entry_point','originalPrompt':'original_prompt','revisedPrompt':'revised_prompt','revisionReason':'revision_reason'}, {'lessonTitle':'lesson_title','prompt':'revised_prompt','designSummary':'avoid_thinking_replacement'}, {'targetRecordId':'to_group_id','borrowIdea':'feedback_text','suggestion':'feedback_text'}, {'greenRule':'green_items','yellowRule':'yellow_items','redRule':'red_items'}, {'highlight':'takeaway','blocker':'stuck_point','firstStep':'first_action'}]
spec={a:{'sheet':names[i],'fields':cols[i].split(','),'aliases':maps[i]} for i,a in enumerate(old)}
Path('data/sheets_schema.json').write_text(json.dumps(dict(zip(names,[c.split(',') for c in cols])),ensure_ascii=False,indent=2),encoding='utf8')
Path('public/assets/js/sheet-contract.js').write_text('const B3_SHEET_CONTRACT = '+json.dumps(spec,ensure_ascii=False)+';\n',encoding='utf8')
doc=['# B3 正式工作表結構','','以下名稱與欄序完全依照指定清單，不追加共通欄位。','']
for n,c in zip(names,cols):doc += ['## '+n,'','`'+c+'`','']
doc+=['## 使用約定','','timestamp 由伺服器產生。participant_id 是匿名識別碼；group_id 是公開投影組別。settings 不是學員提交表，不提供公開寫入 action。分數為 1–5；Prompt 檢查欄位用 true / false 字串。','', '這份結構沒有 workshopId：一份試算表對應一場工作坊。請在指令碼屬性設定 WORKSHOP_ID（預設 b3-demo），避免其他場次誤讀。recordId 只作提交確認回傳，不新增到表格。','', '舊版表格不可直接套用新欄序。請先備份，依此清單建立新試算表，再設定 SPREADSHEET_ID、執行 setupSheets 並重新部署；舊資料需人工確認欄位意義後搬移。欄位不符會拒絕讀寫，不覆寫原資料。','', '前端既有 camelCase 任務資料由 sheet-adapter.js 轉成正式 snake_case JSON；正式 API 同時接受指定欄位。離線模式仍保留原有任務紀錄格式，作為相同畫面的測試資料庫。','', '尚未填寫的新欄位留空，不推測學員答案。既有案例文字暫存 case_id（舊版相容）；正式案例可提交真正 case_id。feedback 舊版 targetRecordId 暫轉 to_group_id，需由使用者填組別。']
Path('data/sheets_schema.md').write_text('\n'.join(doc),encoding='utf8')
