const {chromium}=require('playwright');
const fs=require('fs');
(async()=>{const browser=await chromium.launch({headless:true,channel:"msedge"});const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
for(const route of ['index','checkin','guide','literacy','lesson','checkout','dashboard','resources']){await page.goto('http://127.0.0.1:8765/'+route+'.html');if(await page.locator('h1').count()!==1)throw Error(route+' missing title');if(await page.locator('nav a').count()!==8)throw Error('navigation');if(await page.locator('[role=progressbar]').count()!==1)throw Error('progress');if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error(route+' overflow');}
await page.goto('http://127.0.0.1:8765/index.html');await page.screenshot({path:'site-desktop.png',fullPage:true});await page.goto('http://127.0.0.1:8765/guide.html');await page.locator('[data-task="3"]').click();if(await page.locator('[data-count]').first().textContent()!=='3')throw Error('progress update');await page.goto('http://127.0.0.1:8765/dashboard.html');if(await page.locator('[data-count]').first().textContent()!=='3')throw Error('progress navigation');await page.locator('#reset-demo').click();
await page.goto('http://127.0.0.1:8765/literacy.html');await page.check('input[value=source]');await page.click('#check-risk');if(!(await page.locator('#risk-result').textContent()).includes('答對'))throw Error('quiz');
await page.goto('http://127.0.0.1:8765/lesson.html');await page.fill('#prompt','測試筆記');await page.locator('[data-save]').first().click();await page.reload();if(await page.inputValue('#prompt')!=='測試筆記')throw Error('note save');
await page.setViewportSize({width:390,height:844});for(const route of ['index','checkin','guide','literacy','lesson','checkout','dashboard','resources']){await page.goto('http://127.0.0.1:8765/'+route+'.html');if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error(route+' mobile overflow');await page.locator('.menu-toggle').click();if(!await page.locator('nav').isVisible())throw Error('mobile nav');}
await page.goto('http://127.0.0.1:8765/index.html');await page.screenshot({path:'site-mobile.png',fullPage:true});if(errors.length)throw Error(errors.join('\n'));console.log('PASS: 8 desktop/mobile routes, navigation, task progress, quiz, note persistence, no page errors.');await browser.close();})();


