const {chromium}=require('playwright');const assert=require('assert');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});const page=await browser.newPage();
await page.goto('http://127.0.0.1:8765/checkin.html');await page.evaluate(()=>{localStorage.clear();sessionStorage.clear();});await page.reload();await page.fill('#expectation','離線學習目標');await page.click('[data-save]');await page.waitForFunction(()=>document.querySelector('[data-submit-status]').textContent.includes('儲存成功'));
let rows=await page.evaluate(()=>JSON.parse(localStorage.getItem('b3-api-records-v1')));assert.equal(rows[0].data.goal,'離線學習目標');assert(rows[0].timestamp);await page.reload();assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('b3-api-records-v1')).length),1);
await page.evaluate(()=>window.B3_CONFIG={APPS_SCRIPT_WEB_APP_URL:'https://script.google.com/macros/s/test/exec',WORKSHOP_ID:'b3-demo',REQUEST_TIMEOUT_MS:50});
await page.route('https://script.google.com/**',async route=>{const req=route.request();assert.equal(req.method(),'POST');assert.equal(req.postDataJSON().action,'submitLearningGoal');await route.fulfill({contentType:'application/json',body:JSON.stringify({ok:true,data:{recordId:'remote-1',timestamp:'now'}})});});await page.click('[data-save]');await page.waitForFunction(()=>document.querySelector('[data-submit-status]').textContent.includes('送出成功'));
await page.unroute('https://script.google.com/**');await page.route('https://script.google.com/**',r=>r.fulfill({contentType:'application/json',body:JSON.stringify({ok:false,error:{message:'拒絕寫入'}})}));await page.fill('#expectation','失敗保留內容');await page.click('[data-save]');await page.waitForFunction(()=>document.querySelector('[data-submit-status]').textContent.includes('拒絕寫入'));assert.equal(await page.inputValue('#expectation'),'失敗保留內容');assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('b3-api-records-v1')).length),1);
await page.unroute('https://script.google.com/**');await page.route('https://script.google.com/**',r=>r.fulfill({contentType:'text/html',body:'Login'}));await page.click('[data-save]');await page.waitForFunction(()=>document.querySelector('[data-submit-status]').textContent.includes('未回傳 JSON'));
await page.evaluate(()=>window.B3_CONFIG={APPS_SCRIPT_WEB_APP_URL:'',WORKSHOP_ID:'b3-demo'});
const dash=await page.evaluate(()=>B3API.getDashboardData());assert.equal(dash.data.submissionCounts.submitLearningGoal,1);
for(const name of ['checkin','guide','literacy','lesson','checkout']){await page.goto('http://127.0.0.1:8765/'+name+'.html');assert.equal(await page.locator('form:not([data-api-action])').count(),0);}
await browser.close();console.log('PASS: local persistence, remote POST JSON, business failure, non-JSON response, input retention, no fallback after remote failure, dashboard, all forms connected.');})();

